### ISSUE TITLE
mykrobe errors with: AttributeError: 'Namespace' object has no attribute 'ont'

### ISSUE THREAD

**Issue by aunderwo** [iqbal-lab/Mykrobe-predictor#120]
Running Python 2.7.11 I get the following error

```
INFO:root:Running AMR prediction with panels data/panels/tb-species-160330.fasta.gz, data/panels/tb-amr-walker_2015.fasta.gz
INFO:root:Running AMR prediction with panels data/panels/tb-species-160330.fasta.gz, data/panels/tb-amr-walker_2015.fasta.gz
Traceback (most recent call last):
  File "../mykrobe/bin/mykrobe", line 9, in <module>
    load_entry_point('mykrobe==0.4.3', 'console_scripts', 'mykrobe')()
  File "/home/local/GEL/anthony/software/mykrobe/lib/python2.7/site-packages/mykrobe-0.4.3-py2.7.egg/mykrobe/mykrobe_predictor.py", line 130, in main
    args.func(parser, args)
  File "/home/local/GEL/anthony/software/mykrobe/lib/python2.7/site-packages/mykrobe-0.4.3-py2.7.egg/mykrobe/mykrobe_predictor.py", line 34, in run_subtool
    run(parser, args)
  File "/home/local/GEL/anthony/software/mykrobe/lib/python2.7/site-packages/mykrobe-0.4.3-py2.7.egg/mykrobe/cmds/amr.py", line 117, in run
    if args.ont:
AttributeError: 'Namespace' object has no attribute 'ont'
```

**Comment by Phelimb** [comment]
Thanks @aunderwo . 

Could you paste the output of `pip freeze` in here? Looks like the version of `mykatlas` a dependancy could be incompatible with this version of mykrobe.

**Comment by aunderwo** [comment]
Hi @Phelimb I think this can be closed. I was trying to install using python setup.py install --prefix=...  in order to install to a non standard location. I can install with pip install and virtualenv so will now try with my newly discovered command of pip install -t
