### ISSUE TITLE
[iqbal-lab/Mykrobe-predictor] IndexError: list index out of range exception on Linux but not Mac (#126)

### ISSUE THREAD

**Issue by ponomarevsy** [iqbal-lab/Mykrobe-predictor#131]
(mykrobeenv) [appbuild@ai-submit1]» pip freeze
biopython==1.70
easybuild-easyblocks==2.9.0
easybuild-easyconfigs==2.9.0
easybuild-framework==2.9.0
future==0.16.0
ga4ghmongo==0.0.1.2
mongoengine==0.13.0
mykatlas==0.6.1
mykrobe==0.5.6
numpy==1.13.1
pymongo==3.4.0
PyVCF==0.6.8
six==1.10.0
vsc-base==2.5.4
vsc-install==0.10.15

Dear Mykrobe-predictor support team:
 
I have recompiled mccortex31 and copied the executable under mykrobe’s bin folder. Sadly, “mykrobe predict” still fails. I wonder if “mykatlas==0.6.1” is an incorrect  version. Will wait for comments from Phelim Bradley (please forward his reply to me). Thanks!
 
» mccortex31 --version
Error: Unrecognised command: --version
usage: mccortex31 <command> [options] <args>
version: mccortex=v0.0.3-482-g22410ea zlib=1.2.8 htslib=1.2.1-250-gfa6ed9a ASSERTS=ON hash=Lookup3 CHECKS=ON k=3..31
 
Commands:   breakpoints  use a trusted assembled genome to call large events
            bubbles      find bubbles in graph which are potential variants
            build        construct cortex graph from FASTA/FASTQ/BAM
            calls2vcf    convert bubble/breakpoint calls to VCF
           check        load and check graph (.ctx) and path (.ctp) files
            clean        clean errors from a graph
            contigs      assemble contigs for a sample
            correct      error correct reads
            coverage     print contig coverage
            dist         make colour kmer distance matrix
            index        index a sorted cortex graph file
            inferedges   infer graph edges between kmers before calling `thread`
            join         combine graphs, filter graph intersections
            links        clean and plot link files (.ctp)
            pjoin        merge path files (.ctp)
            popbubbles   pop bubbles in the population graph
            pview        text view of a cortex path file (.ctp)
            reads        filter reads against a graph
            rmsubstr     reduce set of strings to remove substrings
            server       interactively query the graph
            sort         sort the kmers in a graph file
            subgraph     filter a subgraph using seed kmers
            thread       thread reads through cleaned graph to make links
            uniqkmers    generate random unique kmers
            unitigs      pull out unitigs in FASTA, DOT or GFA format
            vcfcov       coverage of a VCF against cortex graphs
            vcfgeno      genotype a VCF after running vcfcov
            view         text view of a cortex graph file (.ctx)
 
  Type a command with no arguments to see help.
 
Common Options:
  -h, --help            Help message
  -q, --quiet           Silence status output normally printed to STDERR
  -f, --force           Overwrite output files if they already exist
  -m, --memory <M>      Memory e.g. 1GB [default: 1GB]
  -n, --nkmers <H>      Hash entries [default: 4M, ~4 million]
  -t, --threads <T>     Limit on proccessing threads [default: 2]
  -o, --out <file>      Output file
  -p, --paths <in.ctp>  Links file to load (can specify multiple times)
 
(mykrobeenv) [appbuild@ai-submit1](master|✔)» module show mykrobe
-------------------------------------------------------------------
/sysapps/cluster/modules/all/mykrobe/0.5.6-Python-3.5:
 
module-whatis         Description: Mykrobe Predictor analyses the whole genome of a bacterial sample, all within a couple of minutes, and predicts which drugs the infection is resistant to. - Homepage: https://github.com/iqbal-lab/Mykrobe-predictor
conflict           mykrobe
prepend-path           CPATH /sysapps/cluster/software/Anaconda/2.3.0Linux-x86_64/envs/mykrobeenv/include
prepend-path           LD_LIBRARY_PATH /sysapps/cluster/software/Anaconda/2.3.0Linux-x86_64/envs/mykrobeenv/lib
prepend-path           LIBRARY_PATH /sysapps/cluster/software/Anaconda/2.3.0Linux-x86_64/envs/mykrobeenv/lib
prepend-path           MANPATH /sysapps/cluster/software/Anaconda/2.3.0Linux-x86_64/envs/mykrobeenv/share/man
prepend-path           PATH /sysapps/cluster/software/Anaconda/2.3.0Linux-x86_64/envs/mykrobeenv/bin
prepend-path           PKG_CONFIG_PATH /sysapps/cluster/software/Anaconda/2.3.0Linux-x86_64/envs/mykrobeenv/lib/pkgconfig
setenv                        EBROOTGEMINI /sysapps/cluster/software/Anaconda/2.3.0Linux-x86_64/envs/mykrobeenv
setenv                        EBVERSIONGEMINI 0.5.6
prepend-path           PATH /sysapps/cluster/software/Anaconda/2.3.0Linux-x86_64/envs/mykrobeenv
-------------------------------------------------------------------
 
(mykrobeenv) [appbuild@ai-submit1](master|✔)» ls /sysapps/cluster/software/Anaconda/2.3.0Linux-x86_64/envs/mykrobeenv/bin
2to3        easy_install      mykrobe      pydoc3.5           python3-config  vcf_melt
2to3-3.5    easy_install-3.5  openssl      python             pyvenv          vcf_sample_filter.py
activate    f2py              pasteurize   python3            pyvenv-3.5      wheel
atlas       futurize          pip          python3.5          sqlite3         wish8.5
conda       idle3             __pycache__  python3.5-config   tclsh8.5        xz
c_rehash    idle3.5           pydoc        python3.5m         unxz
deactivate  mccortex31        pydoc3       python3.5m-config  vcf_filter.py
 
(mykrobeenv) [appbuild@ai-submit1](master|✔)» which mccortex31
~/eb_files/Mykrobe-predictor/Mykrobe-predictor/mccortex/bin/mccortex31
 
(mykrobeenv) [appbuild@ai-submit1](master|✔)» cp ~/eb_files/Mykrobe-predictor/Mykrobe-predictor/mccortex/bin/mccortex31 /sysapps/cluster/software/Anaconda/2.3.0Linux-x86_64/envs/mykrobeenv/bin/.
 
(mykrobeenv) [appbuild@ai-submit1](master|✔)» mykrobe predict SRR5486866 tb --seq /hpcdata/bcbb/tbportal/genomics/SequencingCenterDownloads/Borstel/Romania_50samples/TBprofiler/SRR5486866_1.fastq.gz
INFO:root:Running AMR prediction with panels data/panels/tb-species-170421.fasta.gz, data/panels/tb-walker-probe-set-feb-09-2017.fasta.gz
Traceback (most recent call last):
  File "/sysapps/cluster/software/Anaconda/2.3.0Linux-x86_64/envs/mykrobeenv/bin/mykrobe", line 11, in <module>
    sys.exit(main())
  File "/sysapps/cluster/software/Anaconda/2.3.0Linux-x86_64/envs/mykrobeenv/lib/python3.5/site-packages/mykrobe/mykrobe_predictor.py", line 125, in main
    args.func(parser, args)
  File "/sysapps/cluster/software/Anaconda/2.3.0Linux-x86_64/envs/mykrobeenv/lib/python3.5/site-packages/mykrobe/mykrobe_predictor.py", line 34, in run_subtool
    run(parser, args)
  File "/sysapps/cluster/software/Anaconda/2.3.0Linux-x86_64/envs/mykrobeenv/lib/python3.5/site-packages/mykrobe/cmds/amr.py", line 134, in run
    cp.run()
  File "/sysapps/cluster/software/Anaconda/2.3.0Linux-x86_64/envs/mykrobeenv/lib/python3.5/site-packages/mykatlas/typing/typer/genotyper.py", line 74, in run
    self._parse_covgs()
  File "/sysapps/cluster/software/Anaconda/2.3.0Linux-x86_64/envs/mykrobeenv/lib/python3.5/site-packages/mykatlas/typing/typer/genotyper.py", line 128, in _parse_covgs
    row)
  File "/sysapps/cluster/software/Anaconda/2.3.0Linux-x86_64/envs/mykrobeenv/lib/python3.5/site-packages/mykatlas/typing/typer/genotyper.py", line 118, in _parse_summary_covgs_row
    return row[0], int(row[2]), int(row[3]), 100 * float(row[4]), int(row[5])
IndexError: list index out of range

**Comment by ponomarevsy** [comment]
A quick update: this somehow fixed itself... Most likely, there was not enough disk space to process the file and/or the path to the FASTA file was incorrect.
