### ISSUE TITLE
confidence_threshold bug

### ISSUE THREAD

**Issue by Takadonet** [iqbal-lab/Mykrobe-predictor#143]
Was getting the following stacktrace when running the latest version of mykrobe on bioconda. (0.5.6)

Example command : mykrobe predict tb_sample tb -1 ERR117639_1.fastq.gz

`Traceback (most recent call last):
  File "/share/apps/conda_env/mykrobe-v0.5.6.0/bin/mykrobe", line 6, in <module>
    sys.exit(mykrobe.mykrobe_predictor.main())
  File "/share/apps/conda_env/mykrobe-v0.5.6.0/lib/python3.5/site-packages/mykrobe/mykrobe_predictor.py", line 125, in main
    args.func(parser, args)
  File "/share/apps/conda_env/mykrobe-v0.5.6.0/lib/python3.5/site-packages/mykrobe/mykrobe_predictor.py", line 34, in run_subtool
    run(parser, args)
  File "/share/apps/conda_env/mykrobe-v0.5.6.0/lib/python3.5/site-packages/mykrobe/cmds/amr.py", line 192, in run
    gt.run()
  File "/share/apps/conda_env/mykrobe-v0.5.6.0/lib/python3.5/site-packages/mykatlas/typing/typer/genotyper.py", line 300, in run
    self._type()
  File "/share/apps/conda_env/mykrobe-v0.5.6.0/lib/python3.5/site-packages/mykatlas/typing/typer/genotyper.py", line 304, in _type
    self._type_variants()
  File "/share/apps/conda_env/mykrobe-v0.5.6.0/lib/python3.5/site-packages/mykatlas/typing/typer/genotyper.py", line 338, in _type_variants
    call = gt.type(probe_coverages, variant=probe_name)
  File "/share/apps/conda_env/mykrobe-v0.5.6.0/lib/python3.5/site-packages/mykatlas/typing/typer/variant.py", line 77, in type
    variant_probe_coverage, variant))
  File "/share/apps/conda_env/mykrobe-v0.5.6.0/lib/python3.5/site-packages/mykatlas/typing/typer/variant.py", line 119, in _type_variant_probe_coverages
    if "LOW_GT_CONF" in self.filters and (confidence < self.confidence_threshold):
TypeError: unorderable types: int() < NoneType()
`

It will not work with any of my test datasets and is only resolved by passing a value to --min-variant_conf .
Temporary workaround example would be mykrobe predict tb_sample tb -1 ERR117639_1.fastq.gz --min_variant_conf 0

**Comment by iqbal-lab** [comment]
I'm sorry this issue has been ignored. We're about to move mykrobe to a new codebase and repo. When that is live, I'll return, close this issue and point you at the new code.

**Comment by Phelimb** [comment]
@Takadonet This may be fixed in https://github.com/Mykrobe-tools/mykrobe
