### ISSUE TITLE
Type Error : Write()

### ISSUE THREAD

**Issue by idolawoye** [iqbal-lab/Mykrobe-predictor#148]
I installed mykrobe on my PC which works and runs fine, but now when I installed it on the server I get this error when I try to run an analysis:
```sys.stdout.write(nextline)                                                                                                                                      TypeError: write() argument must be str, not bytes```
Kindly assist me on what to do.

**Comment by idolawoye** [comment]
I have this version of mykrobe v0.5.6-0-gbd7923a-dirty installed on the server.
I ran it using this command: ```mykrobe predict ERR552236 tb --seq ERR552236_1.fastq.gz.fastp --threads 16``` on one of the TB strains I have. Below is what was shown on-screen:

```
INFO:root:Running AMR prediction with panels data/panels/tb-species-170421.fasta.gz, data/panels/tb-walker-probe-set-feb-09-2017.fasta.gz
DEBUG:mykatlas.cortex.mccortex:Setting path to mccortex exacutable
DEBUG:mykatlas.cortex.mccortex:Suggested path to mccortex exacutable is invalid: mccortex31
DEBUG:mykatlas.cortex.mccortex:Checking fallback mccortex exacutable file path: /usr/local/bin/mccortex31
DEBUG:mykatlas.cortex.mccortex:Valid path to mccortex exacutable found: /usr/local/bin/mccortex31
DEBUG:mykatlas.cortex.mccortex:Running coverages command:
/usr/local/bin/mccortex31 geno -t 1 -m 1GB -k 21 -o tmp/ERR552236-21_tb-species-170421-tb-walker-probe-set-feb-09-2017.covgs -I atlas/data/skeletons/tb-species-170421-tb-walker-probe-set-feb-09-2017_21.ctx -s ERR552236-21 -1 ERR552236_1.fastq.gz.fastp -c /usr/local/lib/python3.5/dist-packages/mykrobe/data/panels/tb-species-170421.fasta.gz -c /usr/local/lib/python3.5/dist-packages/mykrobe/data/panels/tb-walker-probe-set-feb-09-2017.fasta.gz tmp/ERR552236-21_tb-species-170421-tb-walker-probe-set-feb-09-2017.ctx
Traceback (most recent call last):
  File "/usr/local/bin/mykrobe", line 11, in <module>
    load_entry_point('mykrobe==0.5.6', 'console_scripts', 'mykrobe')()
  File "/usr/local/lib/python3.5/dist-packages/mykrobe/mykrobe_predictor.py", line 125, in main
    args.func(parser, args)
  File "/usr/local/lib/python3.5/dist-packages/mykrobe/mykrobe_predictor.py", line 34, in run_subtool
    run(parser, args)
  File "/usr/local/lib/python3.5/dist-packages/mykrobe/cmds/amr.py", line 134, in run
    cp.run()
  File "/usr/local/lib/python3.5/dist-packages/mykatlas/typing/typer/genotyper.py", line 73, in run
    self._run_cortex()
  File "/usr/local/lib/python3.5/dist-packages/mykatlas/typing/typer/genotyper.py", line 90, in _run_cortex
    self.mc_cortex_runner.run()
  File "/usr/local/lib/python3.5/dist-packages/mykatlas/cortex/mccortex.py", line 179, in run
    self._run_cortex()
  File "/usr/local/lib/python3.5/dist-packages/mykatlas/cortex/mccortex.py", line 196, in _run_cortex
    self._run_coverage_if_required()
  File "/usr/local/lib/python3.5/dist-packages/mykatlas/cortex/mccortex.py", line 254, in _run_coverage_if_required
    self._execute_command(self.coverages_cmd)
  File "/usr/local/lib/python3.5/dist-packages/mykatlas/cortex/mccortex.py", line 232, in _execute_command
    sys.stdout.write(nextline)
TypeError: write() argument must be str, not bytes
```

**Comment by iqbal-lab** [comment]
Thanks, will look into it. The input file has .fastp on the end. What kind of file is it?

**Comment by idolawoye** [comment]
They are fastq files that have been trimmed using fastp. They work fine with mykrobe on my PC
