### ISSUE TITLE
--ont flag gives error message

### ISSUE THREAD

**Issue by cytang19** [iqbal-lab/Mykrobe-predictor#151]
Hi, I encounter python ValueError when running the program with flag --ont but it works well without --ont. 

The version I am using is v0.5.6-0-gbd7923a-dirty (installed via conda, Python 2.7.15)
The command used is:
```
python ~/tools/Mykrobe-predictor/mykrobe/mykrobe_predictor.py predict sample tb -1 sample.fasta --mccortex31_path ~/tools/Mykrobe-predictor/mccortex/bin/mccortex31 --ont
```
The error message is:
```
Traceback (most recent call last):
  File "/data/chengyee/tools/Mykrobe-predictor/mykrobe/mykrobe_predictor.py", line 135, in <module>
    main()
  File "/data/chengyee/tools/Mykrobe-predictor/mykrobe/mykrobe_predictor.py", line 126, in main
    args.func(parser, args)
  File "/data/chengyee/tools/Mykrobe-predictor/mykrobe/mykrobe_predictor.py", line 35, in run_subtool
    run(parser, args)
  File "/data/chengyee/anaconda2/lib/python2.7/site-packages/mykrobe/cmds/amr.py", line 192, in run
    gt.run()
  File "/data/chengyee/anaconda2/lib/python2.7/site-packages/mykatlas/typing/typer/genotyper.py", line 300, in run
    self._type()
  File "/data/chengyee/anaconda2/lib/python2.7/site-packages/mykatlas/typing/typer/genotyper.py", line 304, in _type
    self._type_variants()
  File "/data/chengyee/anaconda2/lib/python2.7/site-packages/mykatlas/typing/typer/genotyper.py", line 338, in _type_variants
    call = gt.type(probe_coverages, variant=probe_name)
  File "/data/chengyee/anaconda2/lib/python2.7/site-packages/mykatlas/typing/typer/variant.py", line 77, in type
    variant_probe_coverage, variant))
  File "/data/chengyee/anaconda2/lib/python2.7/site-packages/mykatlas/typing/typer/variant.py", line 125, in _type_variant_probe_coverages
    int(i) for i in gt.split("/")],
ValueError: invalid literal for int() with base 10: '-'
```
Please advice.
Thanks,
Cheng

**Comment by Phelimb** [comment]
@cytang19 could you reinstall with the latest version from https://github.com/Mykrobe-tools/mykrobe and see if this resolves your issue?

**Comment by cytang19** [comment]
@Phelimb I installed version 0.6.1 and ran with flag --ont. Now it gave me another error message:
```
Traceback (most recent call last):
  File "/data/chengyee/anaconda2/envs/mykrobe/bin/mykrobe", line 11, in <module>
    sys.exit(main())
  File "/data/chengyee/anaconda2/envs/mykrobe/lib/python3.5/site-packages/mykrobe/cli.py", line 8, in main
    args.func(parser, args)
  File "/data/chengyee/anaconda2/envs/mykrobe/lib/python3.5/site-packages/mykrobe/parser.py", line 40, in run_subtool
    run(parser, args)
  File "/data/chengyee/anaconda2/envs/mykrobe/lib/python3.5/site-packages/mykrobe/cmds/amr.py", line 256, in run
    cp.run()
  File "/data/chengyee/anaconda2/envs/mykrobe/lib/python3.5/site-packages/mykrobe/typing/typer/genotyper.py", line 74, in run
    self._parse_covgs()
  File "/data/chengyee/anaconda2/envs/mykrobe/lib/python3.5/site-packages/mykrobe/typing/typer/genotyper.py", line 127, in _parse_covgs
    row)
  File "/data/chengyee/anaconda2/envs/mykrobe/lib/python3.5/site-packages/mykrobe/typing/typer/genotyper.py", line 117, in _parse_summary_covgs_row
    return row[0], int(row[2]), int(row[3]), 100 * float(row[4]), int(row[5]), int(row[6])
IndexError: list index out of range
```
This error occurred with and without '--ont'. Any advise on how to resolve this?
