### ISSUE TITLE
Index error on version 0.6.1

### ISSUE THREAD

**Issue by cytang19** [iqbal-lab/Mykrobe-predictor#154]
#151 
@Phelimb I installed version 0.6.1 and ran with flag --ont. Now it gave me another error message:
```
Traceback (most recent call last):
  File "/data/chengyee/anaconda2/envs/mykrobe/bin/mykrobe", line 11, in <module>
    sys.exit(main())
  File "/data/chengyee/anaconda2/envs/mykrobe/lib/python3.5/site-packages/mykrobe/cli.py", line 8, in main
    args.func(parser, args)
  File "/data/chengyee/anaconda2/envs/mykrobe/lib/python3.5/site-packages/mykrobe/parser.py", line 40, in run_subtool
    run(parser, args)
  File "/data/chengyee/anaconda2/envs/mykrobe/lib/python3.5/site-packages/mykrobe/cmds/amr.py", line 256, in run
    cp.run()
  File "/data/chengyee/anaconda2/envs/mykrobe/lib/python3.5/site-packages/mykrobe/typing/typer/genotyper.py", line 74, in run
    self._parse_covgs()
  File "/data/chengyee/anaconda2/envs/mykrobe/lib/python3.5/site-packages/mykrobe/typing/typer/genotyper.py", line 127, in _parse_covgs
    row)
  File "/data/chengyee/anaconda2/envs/mykrobe/lib/python3.5/site-packages/mykrobe/typing/typer/genotyper.py", line 117, in _parse_summary_covgs_row
    return row[0], int(row[2]), int(row[3]), 100 * float(row[4]), int(row[5]), int(row[6])
IndexError: list index out of range
```
This error occurred with and without '--ont'. Any advise on how to resolve this?

**Comment by Phelimb** [comment]
Hi @cytang19 , 

It sounds like you might have installed the wrong version of `mccortex`. 

The version must be the `geno_kmer_count` branch from `https://github.com/phelimb/mccortex`. See https://github.com/Mykrobe-tools/mykrobe/blob/master/setup.py#L27.

**Comment by cytang19** [comment]
Thanks for the guidance. It is working now. However, looking at the drug resistance profile, the results from version 0.6.1 (with and without --ont) and mykrobe v0.5.6-0-gbd7923a-dirty (without --ont) are different whereby v0.5.6 has consistent result with lab test but not v0.6.1. That is my user experience analysing one sample.

**Comment by Phelimb** [comment]
Thanks Cheng. If you'd like to let us know the inconsistency in more detail that would be useful. However, it can difficult to interpret if there's an issue with single sample results. v0.6.1 has been well tested on real data though.
